# Generated by Django 3.0.6 on 2020-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UgcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('identity', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=10, verbose_name='真实姓名')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('phone', models.IntegerField(null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': 'ugc用户表',
                'verbose_name_plural': 'ugc用户表',
                'db_table': 'ugc_user',
                'unique_together': {('email', 'phone')},
            },
        ),
    ]
