# Generated by Django 3.0.6 on 2020-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_home', '0002_ugcuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
