# Generated by Django 3.0.6 on 2020-06-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_home', '0003_auto_20200605_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='用户名'),
        ),
    ]
