# Generated by Django 3.0.6 on 2020-06-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_home', '0004_auto_20200605_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
