# Generated by Django 3.0.6 on 2020-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_home', '0005_ugcuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
