# Generated by Django 3.0.6 on 2020-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_mod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcmod',
            name='content',
            field=models.TextField(verbose_name='mod内容'),
        ),
    ]
