# Generated by Django 3.0.6 on 2020-06-11 08:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_mod', '0002_modcomment_moduser_ugcmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcmod',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='mod内容'),
        ),
    ]
