# Generated by Django 3.0.6 on 2020-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_mod', '0003_auto_20200611_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcmod',
            name='main_pic',
            field=models.ImageField(default='faf', upload_to='mod_pic'),
            preserve_default=False,
        ),
    ]
