# Generated by Django 3.0.6 on 2020-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_mod', '0004_ugcmod_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcmod',
            name='main_pic',
            field=models.ImageField(upload_to='mod_pic', verbose_name='展示图片'),
        ),
    ]
