# Generated by Django 3.0.6 on 2020-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0004_ugcserver_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugcserver',
            name='server_password',
            field=models.CharField(max_length=128, null=True, verbose_name='服务器密码'),
        ),
    ]
