# Generated by Django 3.0.6 on 2020-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0005_auto_20200713_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcserver',
            name='is_deadline',
            field=models.SmallIntegerField(default=0, verbose_name='是否到期'),
            preserve_default=False,
        ),
    ]
