# Generated by Django 3.0.6 on 2020-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0006_ugcserver_is_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcserver',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=40, verbose_name='服务器ip'),
            preserve_default=False,
        ),
    ]
