# Generated by Django 3.0.6 on 2020-07-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0007_ugcserver_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcserver',
            name='region',
            field=models.CharField(default='beijing', max_length=20, verbose_name='地区'),
            preserve_default=False,
        ),
    ]
