# Generated by Django 3.0.6 on 2020-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0008_ugcserver_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugcserver',
            name='is_authenticate_password',
            field=models.SmallIntegerField(default=0, verbose_name='是否开启密码验证'),
            preserve_default=False,
        ),
    ]
