# Generated by Django 3.0.6 on 2020-07-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0010_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '腾讯云服务器表', 'verbose_name_plural': '腾讯云服务器表'},
        ),
        migrations.AlterModelTable(
            name='server',
            table='tencent_server',
        ),
    ]
