# Generated by Django 3.0.6 on 2020-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0012_server_rest_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='rest_disk',
            field=models.IntegerField(db_index=True, verbose_name='空闲硬盘'),
        ),
    ]
