# Generated by Django 3.0.6 on 2020-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc_server', '0013_auto_20200718_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.CharField(default='匾北京', max_length=40, verbose_name='地区'),
            preserve_default=False,
        ),
    ]
